services:
  - type: web
    name: sras-django
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn SRAS_Project.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: sras_db
          property: connectionString

databases:
  - name: sras_db
    databaseName: sras_django
    plan: free